version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: authforge-postgres
    environment:
      POSTGRES_DB: authforge
      POSTGRES_USER: authforge
      POSTGRES_PASSWORD: authforge
    ports:
      - "5432:5432"
    volumes:
      - authforge-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL" , "pg_isready -U authforge"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  authforge-data:
